services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_ROOT_USERNAME=root
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_ROOT_USERNAME=root
      - MONGO_ROOT_PASSWORD=root
      - MONGO_HOST=mongodb:27017
      - TOKEN_SECRET=Ree4kai4uxie0see5Aixai2ath5lie8E
    depends_on:
      - mongodb